# Generated by Django 4.1.4 on 2022-12-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeepVision", "0002_input_images_date_input_images_label"),
    ]

    operations = [
        migrations.RemoveField(model_name="input_images", name="label",),
    ]
