# Generated by Django 4.1.4 on 2022-12-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeepVision", "0003_remove_input_images_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="input_images",
            name="label",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
